/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.tartarus.artists;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Soerakraven
 */
public class ShowCustomerEditUI extends javax.swing.JFrame {
    public DetailsWindowUI novo = new DetailsWindowUI();
    int index = 0;
    /**
     * Creates new form ShowCustomerEditUI
     */
    public ShowCustomerEditUI() {
        initComponents();
    }
    public int MOCCounter(){
        int cont=0;
        if(METHOD_OF_CONTACT_DA.isSelected() == true){
            cont++;
        }
        if(METHOD_OF_CONTACT_FA.isSelected() == true){
            cont++;
        }
        if(METHOD_OF_CONTACT_TELEGRAM.isSelected() == true){
            cont++;
        }
        if(METHOD_OF_CONTACT_DISCORD.isSelected() == true){
            cont++;
        }
        if(METHOD_OF_CONTACT_OTHER.isSelected() == true){
            cont++;
        }
        return cont;
    }
    public void WritesCustomerInfo(int index){
        this.index = index;
        Customer cu = new Customer();
        cu = ManageCustomerList.cuzt.get(index);
        USERNAME_TEXT.setText(cu.GetUsername());
        for(int i=0;i<cu.GetMOC().length;i++){
            if(cu.GetMOC()[i].equals("Discord")){
                METHOD_OF_CONTACT_DISCORD.setSelected(true);
            }else if(cu.GetMOC()[i].equals("Telegram")){
                METHOD_OF_CONTACT_TELEGRAM.setSelected(true);
            }else if(cu.GetMOC()[i].equals("FurAffinity")){
                METHOD_OF_CONTACT_FA.setSelected(true);
            }else if(cu.GetMOC()[i].equals("Deviantart")){
                METHOD_OF_CONTACT_DA.setSelected(true);
            }else{
                METHOD_OF_CONTACT_OTHER.setSelected(true);
                METHOD_OF_CONTACT_OTHER_TEXT.setText(cu.GetMOC()[i]);
            }
        }
        if(cu.GetPreviousCommissioner().equals("Yes")){
            PREVIOUS_COMMISSIONER_YES.setSelected(true);
        }else{
            PREVIOUS_COMMISSIONER_NO.setSelected(true);
        }
        String daydoc = ManageCustomerList.ReturnsDateDay(cu.GetDateOfCommission());
        String monthdoc = ManageCustomerList.ReturnsDateMonth(cu.GetDateOfCommission());
        String yeardoc = ManageCustomerList.ReturnsDateYear(cu.GetDateOfCommission());
        DATE_OF_COMMISSION_DAY.setSelectedItem(daydoc);
        DATE_OF_COMMISSION_MONTH.setSelectedItem(monthdoc);
        DATE_OF_COMMISSION_YEAR.setSelectedItem(yeardoc);
        String daydop = ManageCustomerList.ReturnsDateDay(cu.GetDateOfCommission());
        String monthdop = ManageCustomerList.ReturnsDateMonth(cu.GetDateOfCommission());
        String yeardop = ManageCustomerList.ReturnsDateYear(cu.GetDateOfCommission());
        DATE_OF_PAYMENT_DAY.setSelectedItem(daydop);
        DATE_OF_PAYMENT_MONTH.setSelectedItem(monthdop);
        DATE_OF_PAYMENT_YEAR.setSelectedItem(yeardop);
        INVOICE_NUMBER_NUMBER.setText(cu.GetNumberInvoice());
        PRICE_CHARGED_CURRENCY.setSelectedItem(cu.GetPriceChargedCurrency());
        PRICE_CHARGED_AMMOUNT.setText(cu.GetPriceCharged());
        novo.SetText(cu.GetDetails());
        if(cu.GetCompletion().equals("Yes")==true){
            COMMISSION_COMPLETE_YES.setSelected(true);
        }else{
            COMMISSION_COMPLETE_NO.setSelected(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PREVIOUS_COMISSIONER_BUTTON_GROUP = new javax.swing.ButtonGroup();
        COMMISSION_COMPLETE_BUTTON_GROUP = new javax.swing.ButtonGroup();
        ARTIST_USERNAME_PANEL = new javax.swing.JPanel();
        USERNAME = new javax.swing.JLabel();
        USERNAME_TEXT = new javax.swing.JTextField();
        ARTIST_MOC_PANEL = new javax.swing.JPanel();
        METHOD_OF_CONTACT = new javax.swing.JLabel();
        METHOD_OF_CONTACT_DISCORD = new javax.swing.JCheckBox();
        METHOD_OF_CONTACT_TELEGRAM = new javax.swing.JCheckBox();
        METHOD_OF_CONTACT_FA = new javax.swing.JCheckBox();
        METHOD_OF_CONTACT_DA = new javax.swing.JCheckBox();
        METHOD_OF_CONTACT_OTHER = new javax.swing.JCheckBox();
        METHOD_OF_CONTACT_OTHER_TEXT = new javax.swing.JTextField();
        ARTIST_PREVIOUS_PANEL = new javax.swing.JPanel();
        PREVIOUS_COMMISSIONER = new javax.swing.JLabel();
        PREVIOUS_COMMISSIONER_YES = new javax.swing.JRadioButton();
        PREVIOUS_COMMISSIONER_NO = new javax.swing.JRadioButton();
        ARTIST_DATE_PANEL = new javax.swing.JPanel();
        DATE_OF_COMMISSION = new javax.swing.JLabel();
        DATE_OF_COMMISSION_DAY = new javax.swing.JComboBox<>();
        BARRINHA1 = new javax.swing.JLabel();
        DATE_OF_COMMISSION_MONTH = new javax.swing.JComboBox<>();
        BARRINHA2 = new javax.swing.JLabel();
        DATE_OF_COMMISSION_YEAR = new javax.swing.JComboBox<>();
        ARTIST_PAYMENT_PANEL = new javax.swing.JPanel();
        DATE_OF_PAYMENT = new javax.swing.JLabel();
        DATE_OF_PAYMENT_DAY = new javax.swing.JComboBox<>();
        BARRINHA3 = new javax.swing.JLabel();
        DATE_OF_PAYMENT_MONTH = new javax.swing.JComboBox<>();
        BARRINHA4 = new javax.swing.JLabel();
        DATE_OF_PAYMENT_YEAR = new javax.swing.JComboBox<>();
        INVOICE_NUMBER = new javax.swing.JLabel();
        INVOICE_NUMBER_NUMBER = new javax.swing.JTextField();
        PRICE_CHARGED = new javax.swing.JLabel();
        PRICE_CHARGED_CURRENCY = new javax.swing.JComboBox<>();
        PRICE_CHARGED_AMMOUNT = new javax.swing.JTextField();
        ARTIST_DETAILS_PANEL = new javax.swing.JPanel();
        WRITTEN_DETAILS = new javax.swing.JLabel();
        OPEN_DETAILS_WINDOW_BUTTON = new javax.swing.JButton();
        ARTIST_COMPLETION_PANEL = new javax.swing.JPanel();
        COMMISSION_COMPLETE = new javax.swing.JLabel();
        COMMISSION_COMPLETE_YES = new javax.swing.JRadioButton();
        COMMISSION_COMPLETE_NO = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ARTIST_USERNAME_PANEL.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Username"));

        USERNAME.setBackground(new java.awt.Color(255, 255, 255));
        USERNAME.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        USERNAME.setText("Commissioner Username");
        USERNAME.setToolTipText("");

        USERNAME_TEXT.setForeground(new java.awt.Color(113, 113, 113));
        USERNAME_TEXT.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        USERNAME_TEXT.setSelectedTextColor(new java.awt.Color(255, 255, 0));
        USERNAME_TEXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USERNAME_TEXTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ARTIST_USERNAME_PANELLayout = new javax.swing.GroupLayout(ARTIST_USERNAME_PANEL);
        ARTIST_USERNAME_PANEL.setLayout(ARTIST_USERNAME_PANELLayout);
        ARTIST_USERNAME_PANELLayout.setHorizontalGroup(
            ARTIST_USERNAME_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ARTIST_USERNAME_PANELLayout.createSequentialGroup()
                .addComponent(USERNAME)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(USERNAME_TEXT))
        );
        ARTIST_USERNAME_PANELLayout.setVerticalGroup(
            ARTIST_USERNAME_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ARTIST_USERNAME_PANELLayout.createSequentialGroup()
                .addGroup(ARTIST_USERNAME_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(USERNAME)
                    .addComponent(USERNAME_TEXT, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        ARTIST_MOC_PANEL.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Contact"));

        METHOD_OF_CONTACT.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        METHOD_OF_CONTACT.setText("Method of contact");

        METHOD_OF_CONTACT_DISCORD.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        METHOD_OF_CONTACT_DISCORD.setText("Discord");
        METHOD_OF_CONTACT_DISCORD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                METHOD_OF_CONTACT_DISCORDActionPerformed(evt);
            }
        });

        METHOD_OF_CONTACT_TELEGRAM.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        METHOD_OF_CONTACT_TELEGRAM.setText("Telegram");

        METHOD_OF_CONTACT_FA.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        METHOD_OF_CONTACT_FA.setText("FurAffinity");

        METHOD_OF_CONTACT_DA.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        METHOD_OF_CONTACT_DA.setText("Deviantart");

        METHOD_OF_CONTACT_OTHER.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        METHOD_OF_CONTACT_OTHER.setText("Other");
        METHOD_OF_CONTACT_OTHER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                METHOD_OF_CONTACT_OTHERActionPerformed(evt);
            }
        });

        METHOD_OF_CONTACT_OTHER_TEXT.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        METHOD_OF_CONTACT_OTHER_TEXT.setEnabled(false);
        METHOD_OF_CONTACT_OTHER_TEXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                METHOD_OF_CONTACT_OTHER_TEXTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ARTIST_MOC_PANELLayout = new javax.swing.GroupLayout(ARTIST_MOC_PANEL);
        ARTIST_MOC_PANEL.setLayout(ARTIST_MOC_PANELLayout);
        ARTIST_MOC_PANELLayout.setHorizontalGroup(
            ARTIST_MOC_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ARTIST_MOC_PANELLayout.createSequentialGroup()
                .addGroup(ARTIST_MOC_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ARTIST_MOC_PANELLayout.createSequentialGroup()
                        .addComponent(METHOD_OF_CONTACT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(METHOD_OF_CONTACT_DISCORD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(METHOD_OF_CONTACT_TELEGRAM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(METHOD_OF_CONTACT_OTHER))
                    .addGroup(ARTIST_MOC_PANELLayout.createSequentialGroup()
                        .addComponent(METHOD_OF_CONTACT_FA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(METHOD_OF_CONTACT_DA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(METHOD_OF_CONTACT_OTHER_TEXT)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ARTIST_MOC_PANELLayout.setVerticalGroup(
            ARTIST_MOC_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ARTIST_MOC_PANELLayout.createSequentialGroup()
                .addGroup(ARTIST_MOC_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(METHOD_OF_CONTACT)
                    .addComponent(METHOD_OF_CONTACT_DISCORD)
                    .addComponent(METHOD_OF_CONTACT_TELEGRAM)
                    .addComponent(METHOD_OF_CONTACT_OTHER))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ARTIST_MOC_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(METHOD_OF_CONTACT_FA)
                    .addComponent(METHOD_OF_CONTACT_DA)
                    .addComponent(METHOD_OF_CONTACT_OTHER_TEXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        ARTIST_PREVIOUS_PANEL.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Previous"));

        PREVIOUS_COMMISSIONER.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        PREVIOUS_COMMISSIONER.setText("Previous Customer?");

        PREVIOUS_COMISSIONER_BUTTON_GROUP.add(PREVIOUS_COMMISSIONER_YES);
        PREVIOUS_COMMISSIONER_YES.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        PREVIOUS_COMMISSIONER_YES.setText("Yes");
        PREVIOUS_COMMISSIONER_YES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PREVIOUS_COMMISSIONER_YESActionPerformed(evt);
            }
        });

        PREVIOUS_COMISSIONER_BUTTON_GROUP.add(PREVIOUS_COMMISSIONER_NO);
        PREVIOUS_COMMISSIONER_NO.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        PREVIOUS_COMMISSIONER_NO.setText("No");
        PREVIOUS_COMMISSIONER_NO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PREVIOUS_COMMISSIONER_NOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ARTIST_PREVIOUS_PANELLayout = new javax.swing.GroupLayout(ARTIST_PREVIOUS_PANEL);
        ARTIST_PREVIOUS_PANEL.setLayout(ARTIST_PREVIOUS_PANELLayout);
        ARTIST_PREVIOUS_PANELLayout.setHorizontalGroup(
            ARTIST_PREVIOUS_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ARTIST_PREVIOUS_PANELLayout.createSequentialGroup()
                .addComponent(PREVIOUS_COMMISSIONER)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PREVIOUS_COMMISSIONER_YES)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PREVIOUS_COMMISSIONER_NO)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ARTIST_PREVIOUS_PANELLayout.setVerticalGroup(
            ARTIST_PREVIOUS_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ARTIST_PREVIOUS_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(PREVIOUS_COMMISSIONER, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(PREVIOUS_COMMISSIONER_YES)
                .addComponent(PREVIOUS_COMMISSIONER_NO))
        );

        ARTIST_DATE_PANEL.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Date of closure"));

        DATE_OF_COMMISSION.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        DATE_OF_COMMISSION.setText("Date of Commission");

        DATE_OF_COMMISSION_DAY.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        DATE_OF_COMMISSION_DAY.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        BARRINHA1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BARRINHA1.setText("/");

        DATE_OF_COMMISSION_MONTH.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        DATE_OF_COMMISSION_MONTH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        BARRINHA2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BARRINHA2.setText("/");

        DATE_OF_COMMISSION_YEAR.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        DATE_OF_COMMISSION_YEAR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028" }));

        javax.swing.GroupLayout ARTIST_DATE_PANELLayout = new javax.swing.GroupLayout(ARTIST_DATE_PANEL);
        ARTIST_DATE_PANEL.setLayout(ARTIST_DATE_PANELLayout);
        ARTIST_DATE_PANELLayout.setHorizontalGroup(
            ARTIST_DATE_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ARTIST_DATE_PANELLayout.createSequentialGroup()
                .addComponent(DATE_OF_COMMISSION)
                .addGap(33, 33, 33)
                .addComponent(DATE_OF_COMMISSION_DAY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(BARRINHA1)
                .addGap(2, 2, 2)
                .addComponent(DATE_OF_COMMISSION_MONTH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(BARRINHA2)
                .addGap(2, 2, 2)
                .addComponent(DATE_OF_COMMISSION_YEAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 41, Short.MAX_VALUE))
        );
        ARTIST_DATE_PANELLayout.setVerticalGroup(
            ARTIST_DATE_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ARTIST_DATE_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(DATE_OF_COMMISSION)
                .addComponent(DATE_OF_COMMISSION_DAY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(DATE_OF_COMMISSION_MONTH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(DATE_OF_COMMISSION_YEAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(BARRINHA1)
                .addComponent(BARRINHA2))
        );

        ARTIST_PAYMENT_PANEL.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Payment"));

        DATE_OF_PAYMENT.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        DATE_OF_PAYMENT.setText("Date of Payment");

        DATE_OF_PAYMENT_DAY.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        DATE_OF_PAYMENT_DAY.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        BARRINHA3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BARRINHA3.setText("/");

        DATE_OF_PAYMENT_MONTH.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        DATE_OF_PAYMENT_MONTH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        BARRINHA4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BARRINHA4.setText("/");

        DATE_OF_PAYMENT_YEAR.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        DATE_OF_PAYMENT_YEAR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028" }));
        DATE_OF_PAYMENT_YEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DATE_OF_PAYMENT_YEARActionPerformed(evt);
            }
        });

        INVOICE_NUMBER.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        INVOICE_NUMBER.setText("Number of Invoice");

        INVOICE_NUMBER_NUMBER.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        PRICE_CHARGED.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        PRICE_CHARGED.setText("Price Charged");

        PRICE_CHARGED_CURRENCY.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        PRICE_CHARGED_CURRENCY.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADP", "AED", "AFA", "AFN", "ALK", "ALL", "AMD", "ANG", "AOA", "AOK", "AON", "AOR", "ARA", "ARP", "ARS", "ARY", "ATS", "AUD", "AWG", "AYM", "AZM", "AZN", "BAD", "BAM", "BBD", "BDT", "BEC", "BEF", "BEL", "BGJ", "BGK", "BGL", "BGN", "BHD", "BIF", "BMD", "BND", "BOB", "BOP", "BOV", "BRB", "BRC", "BRE", "BRL", "BRN", "BRR", "BSD", "BTN", "BUK", "BWP", "BYB", "BYN", "BYR", "BZD", "CAD", "CDF", "CHC", "CHE", "CHF", "CHW", "CLF", "CLP", "CNX", "CNY", "COP", "COU", "CRC", "CSD", "CSJ", "CSK", "CUC", "CUP", "CVE", "CYP", "CZK", "DDM", "DEM", "DJF", "DKK", "DOP", "DZD", "ECS", "ECV", "EEK", "EGP", "ERN", "ESA", "ESB", "ESP", "ETB", "EUR", "FIM", "FJD", "FKP", "FRF", "GBP", "GEK", "GEL", "GHC", "GHP", "GHS", "GIP", "GMD", "GNE", "GNF", "GNS", "GQE", "GRD", "GTQ", "GWE", "GWP", "GYD", "HKD", "HNL", "HRD", "HRK", "HTG", "HUF", "IDR", "IEP", "ILP", "ILR", "ILS", "INR", "IQD", "IRR", "ISJ", "ISK", "ITL", "JMD", "JOD", "JPY", "KES", "KGS", "KHR", "KMF", "KPW", "KRW", "KWD", "KYD", "KZT", "LAJ", "LAK", "LBP", "LKR", "LRD", "LSL", "LSM", "LTL", "LTT", "LUC", "LUF", "LUL", "LVL", "LVR", "LYD", "MAD", "MDL", "MGA", "MGF", "MKD", "MLF", "MMK", "MNT", "MOP", "MRO", "MTL", "MTP", "MUR", "MVQ", "MVR", "MWK", "MXN", "MXP", "MXV", "MYR", "MZE", "MZM", "MZN", "NAD", "NGN", "NIC", "NIO", "NLG", "NOK", "NPR", "NZD", "OMR", "PAB", "PEH", "PEI", "PEN", "PES", "PGK", "PHP", "PKR", "PLN", "PLZ", "PTE", "PYG", "QAR", "RHD", "ROK", "ROL", "RON", "RSD", "RUB", "RUR", "RWF", "SAR", "SBD", "SCR", "SDD", "SDG", "SDP", "SEK", "SGD", "SHP", "SIT", "SKK", "SLL", "SOS", "SRD", "SRG", "SSP", "STD", "SUR", "SVC", "SYP", "SZL", "THB", "TJR", "TJS", "TMM", "TMT", "TND", "TOP", "TPE", "TRL", "TRY", "TTD", "TWD", "TZS", "UAH", "UAK", "UGS", "UGW", "UGX", "USD", "USN", "USS", "UYI", "UYN", "UYP", "UYU", "UZS", "VEB", "VEF", "VNC", "VND", "VUV", "WST", "XAF", "XAG", "XAU", "XBA", "XBB", "XBC", "XBD", "XCD", "XDR", "XEU", "XFO", "XFU", "XOF", "XPD", "XPF", "XPT", "XRE", "XSU", "XTS", "XUA", "XXX", "YDD", "YER", "YUD", "YUM", "YUN", "ZAL", "ZAR", "ZMK", "ZMW", "ZRN", "ZRZ", "ZWC", "ZWD", "ZWL", "ZWN", "ZWR" }));
        PRICE_CHARGED_CURRENCY.setSelectedIndex(248);

        PRICE_CHARGED_AMMOUNT.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        javax.swing.GroupLayout ARTIST_PAYMENT_PANELLayout = new javax.swing.GroupLayout(ARTIST_PAYMENT_PANEL);
        ARTIST_PAYMENT_PANEL.setLayout(ARTIST_PAYMENT_PANELLayout);
        ARTIST_PAYMENT_PANELLayout.setHorizontalGroup(
            ARTIST_PAYMENT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ARTIST_PAYMENT_PANELLayout.createSequentialGroup()
                .addGroup(ARTIST_PAYMENT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INVOICE_NUMBER)
                    .addComponent(DATE_OF_PAYMENT)
                    .addGroup(ARTIST_PAYMENT_PANELLayout.createSequentialGroup()
                        .addComponent(PRICE_CHARGED)
                        .addGap(6, 6, 6)
                        .addComponent(PRICE_CHARGED_CURRENCY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ARTIST_PAYMENT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(INVOICE_NUMBER_NUMBER, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DATE_OF_PAYMENT_DAY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PRICE_CHARGED_AMMOUNT, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(BARRINHA3)
                .addGap(3, 3, 3)
                .addComponent(DATE_OF_PAYMENT_MONTH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(BARRINHA4)
                .addGap(2, 2, 2)
                .addComponent(DATE_OF_PAYMENT_YEAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ARTIST_PAYMENT_PANELLayout.setVerticalGroup(
            ARTIST_PAYMENT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ARTIST_PAYMENT_PANELLayout.createSequentialGroup()
                .addGroup(ARTIST_PAYMENT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DATE_OF_PAYMENT)
                    .addComponent(DATE_OF_PAYMENT_DAY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DATE_OF_PAYMENT_MONTH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DATE_OF_PAYMENT_YEAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BARRINHA3)
                    .addComponent(BARRINHA4))
                .addGroup(ARTIST_PAYMENT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ARTIST_PAYMENT_PANELLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(INVOICE_NUMBER_NUMBER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ARTIST_PAYMENT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PRICE_CHARGED_AMMOUNT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PRICE_CHARGED_CURRENCY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PRICE_CHARGED)))
                    .addGroup(ARTIST_PAYMENT_PANELLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(INVOICE_NUMBER)))
                .addContainerGap())
        );

        ARTIST_DETAILS_PANEL.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Details"));

        WRITTEN_DETAILS.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        WRITTEN_DETAILS.setText("Written Details");

        OPEN_DETAILS_WINDOW_BUTTON.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        OPEN_DETAILS_WINDOW_BUTTON.setText("Open details window");
        OPEN_DETAILS_WINDOW_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OPEN_DETAILS_WINDOW_BUTTONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ARTIST_DETAILS_PANELLayout = new javax.swing.GroupLayout(ARTIST_DETAILS_PANEL);
        ARTIST_DETAILS_PANEL.setLayout(ARTIST_DETAILS_PANELLayout);
        ARTIST_DETAILS_PANELLayout.setHorizontalGroup(
            ARTIST_DETAILS_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ARTIST_DETAILS_PANELLayout.createSequentialGroup()
                .addComponent(WRITTEN_DETAILS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OPEN_DETAILS_WINDOW_BUTTON)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ARTIST_DETAILS_PANELLayout.setVerticalGroup(
            ARTIST_DETAILS_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ARTIST_DETAILS_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(OPEN_DETAILS_WINDOW_BUTTON)
                .addComponent(WRITTEN_DETAILS))
        );

        ARTIST_COMPLETION_PANEL.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Completion"));

        COMMISSION_COMPLETE.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        COMMISSION_COMPLETE.setText("Commision complete?");

        COMMISSION_COMPLETE_BUTTON_GROUP.add(COMMISSION_COMPLETE_YES);
        COMMISSION_COMPLETE_YES.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        COMMISSION_COMPLETE_YES.setText("Yes");
        COMMISSION_COMPLETE_YES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COMMISSION_COMPLETE_YESActionPerformed(evt);
            }
        });

        COMMISSION_COMPLETE_BUTTON_GROUP.add(COMMISSION_COMPLETE_NO);
        COMMISSION_COMPLETE_NO.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        COMMISSION_COMPLETE_NO.setText("No");
        COMMISSION_COMPLETE_NO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COMMISSION_COMPLETE_NOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ARTIST_COMPLETION_PANELLayout = new javax.swing.GroupLayout(ARTIST_COMPLETION_PANEL);
        ARTIST_COMPLETION_PANEL.setLayout(ARTIST_COMPLETION_PANELLayout);
        ARTIST_COMPLETION_PANELLayout.setHorizontalGroup(
            ARTIST_COMPLETION_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ARTIST_COMPLETION_PANELLayout.createSequentialGroup()
                .addComponent(COMMISSION_COMPLETE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(COMMISSION_COMPLETE_YES)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(COMMISSION_COMPLETE_NO)
                .addGap(154, 154, 154))
        );
        ARTIST_COMPLETION_PANELLayout.setVerticalGroup(
            ARTIST_COMPLETION_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ARTIST_COMPLETION_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(COMMISSION_COMPLETE)
                .addComponent(COMMISSION_COMPLETE_YES)
                .addComponent(COMMISSION_COMPLETE_NO))
        );

        jButton1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jButton2.setText("CANCEL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ARTIST_USERNAME_PANEL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ARTIST_MOC_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ARTIST_PREVIOUS_PANEL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ARTIST_DATE_PANEL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ARTIST_COMPLETION_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(ARTIST_DETAILS_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ARTIST_PAYMENT_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ARTIST_USERNAME_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(ARTIST_MOC_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(ARTIST_PREVIOUS_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(ARTIST_DATE_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ARTIST_PAYMENT_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ARTIST_DETAILS_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ARTIST_COMPLETION_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void USERNAME_TEXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USERNAME_TEXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_USERNAME_TEXTActionPerformed

    private void METHOD_OF_CONTACT_DISCORDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_METHOD_OF_CONTACT_DISCORDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_METHOD_OF_CONTACT_DISCORDActionPerformed

    private void METHOD_OF_CONTACT_OTHERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_METHOD_OF_CONTACT_OTHERActionPerformed
        if(METHOD_OF_CONTACT_OTHER.isSelected()){
            METHOD_OF_CONTACT_OTHER_TEXT.setEnabled(true);
        }else{
            METHOD_OF_CONTACT_OTHER_TEXT.setEnabled(false);
        }
    }//GEN-LAST:event_METHOD_OF_CONTACT_OTHERActionPerformed

    private void METHOD_OF_CONTACT_OTHER_TEXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_METHOD_OF_CONTACT_OTHER_TEXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_METHOD_OF_CONTACT_OTHER_TEXTActionPerformed

    private void PREVIOUS_COMMISSIONER_YESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PREVIOUS_COMMISSIONER_YESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PREVIOUS_COMMISSIONER_YESActionPerformed

    private void PREVIOUS_COMMISSIONER_NOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PREVIOUS_COMMISSIONER_NOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PREVIOUS_COMMISSIONER_NOActionPerformed

    private void DATE_OF_PAYMENT_YEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DATE_OF_PAYMENT_YEARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DATE_OF_PAYMENT_YEARActionPerformed

    private void OPEN_DETAILS_WINDOW_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OPEN_DETAILS_WINDOW_BUTTONActionPerformed
        novo.setVisible(true);
    }//GEN-LAST:event_OPEN_DETAILS_WINDOW_BUTTONActionPerformed

    private void COMMISSION_COMPLETE_YESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COMMISSION_COMPLETE_YESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_COMMISSION_COMPLETE_YESActionPerformed

    private void COMMISSION_COMPLETE_NOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COMMISSION_COMPLETE_NOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_COMMISSION_COMPLETE_NOActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String[] entradas = new String[10];
        entradas[0] = USERNAME_TEXT.getText();
        int cont2=0;
        entradas[1] = "";
        String[] MOC = new String[MOCCounter()];
        if(METHOD_OF_CONTACT_DA.isSelected() == true){
            MOC[cont2] = METHOD_OF_CONTACT_DA.getText();
            cont2++;
        }
        if(METHOD_OF_CONTACT_FA.isSelected() == true){
            MOC[cont2] = METHOD_OF_CONTACT_FA.getText();
            cont2++;
        }
        if(METHOD_OF_CONTACT_TELEGRAM.isSelected() == true){
            MOC[cont2] = METHOD_OF_CONTACT_TELEGRAM.getText();
            cont2++;
        }
        if(METHOD_OF_CONTACT_DISCORD.isSelected() == true){
            MOC[cont2] = METHOD_OF_CONTACT_DISCORD.getText();
            cont2++;
        }
        if(METHOD_OF_CONTACT_OTHER.isSelected() == true){
            MOC[cont2] = METHOD_OF_CONTACT_OTHER_TEXT.getText();
            cont2++;
        }
        if(PREVIOUS_COMMISSIONER_NO.isSelected() == true){
            entradas[2] = PREVIOUS_COMMISSIONER_NO.getText();
        }else{
            entradas[2] = PREVIOUS_COMMISSIONER_YES.getText();
        }
        entradas[3] = DATE_OF_COMMISSION_DAY.getSelectedItem().toString() + "/" + DATE_OF_COMMISSION_MONTH.getSelectedItem().toString() + "/" + DATE_OF_COMMISSION_YEAR.getSelectedItem().toString();
        entradas[4] = DATE_OF_PAYMENT_DAY.getSelectedItem().toString() + "/" + DATE_OF_PAYMENT_MONTH.getSelectedItem().toString() + "/" + DATE_OF_PAYMENT_YEAR.getSelectedItem().toString();
        entradas[5] = INVOICE_NUMBER_NUMBER.getText();
        entradas[6] = PRICE_CHARGED_CURRENCY.getSelectedItem().toString();
        entradas[7] = PRICE_CHARGED_AMMOUNT.getText();
        entradas[8] = novo.GetText();
        if(COMMISSION_COMPLETE_YES.isSelected()){
            entradas[9] = COMMISSION_COMPLETE_YES.getText();
        }else{
            entradas[9] = COMMISSION_COMPLETE_NO.getText();
        }
        Customer cus = new Customer(entradas[0], MOC, entradas[2], entradas[3], entradas[4], entradas[5], entradas[6], entradas[7], entradas[8], entradas[9]);
        System.out.printf("Replacing file...");
        ManageCustomerList.cuzt.set(index, cus);
        ArchiveCustomer.ReplaceFile(index);
        ShowCustomerUI SU = ComboBoxUI.ReturnsSU();
        SU.CleansText();
        SU.SetText(cus, index, cus.GetDateOfCommission());
        JOptionPane.showMessageDialog(new JFrame(), "Successfully replaced!");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowCustomerEditUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowCustomerEditUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowCustomerEditUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowCustomerEditUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowCustomerEditUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ARTIST_COMPLETION_PANEL;
    private javax.swing.JPanel ARTIST_DATE_PANEL;
    private javax.swing.JPanel ARTIST_DETAILS_PANEL;
    private javax.swing.JPanel ARTIST_MOC_PANEL;
    private javax.swing.JPanel ARTIST_PAYMENT_PANEL;
    private javax.swing.JPanel ARTIST_PREVIOUS_PANEL;
    private javax.swing.JPanel ARTIST_USERNAME_PANEL;
    private javax.swing.JLabel BARRINHA1;
    private javax.swing.JLabel BARRINHA2;
    private javax.swing.JLabel BARRINHA3;
    private javax.swing.JLabel BARRINHA4;
    private javax.swing.JLabel COMMISSION_COMPLETE;
    private javax.swing.ButtonGroup COMMISSION_COMPLETE_BUTTON_GROUP;
    private javax.swing.JRadioButton COMMISSION_COMPLETE_NO;
    private javax.swing.JRadioButton COMMISSION_COMPLETE_YES;
    private javax.swing.JLabel DATE_OF_COMMISSION;
    private javax.swing.JComboBox<String> DATE_OF_COMMISSION_DAY;
    private javax.swing.JComboBox<String> DATE_OF_COMMISSION_MONTH;
    private javax.swing.JComboBox<String> DATE_OF_COMMISSION_YEAR;
    private javax.swing.JLabel DATE_OF_PAYMENT;
    private javax.swing.JComboBox<String> DATE_OF_PAYMENT_DAY;
    private javax.swing.JComboBox<String> DATE_OF_PAYMENT_MONTH;
    private javax.swing.JComboBox<String> DATE_OF_PAYMENT_YEAR;
    private javax.swing.JLabel INVOICE_NUMBER;
    private javax.swing.JTextField INVOICE_NUMBER_NUMBER;
    private javax.swing.JLabel METHOD_OF_CONTACT;
    private javax.swing.JCheckBox METHOD_OF_CONTACT_DA;
    private javax.swing.JCheckBox METHOD_OF_CONTACT_DISCORD;
    private javax.swing.JCheckBox METHOD_OF_CONTACT_FA;
    private javax.swing.JCheckBox METHOD_OF_CONTACT_OTHER;
    private javax.swing.JTextField METHOD_OF_CONTACT_OTHER_TEXT;
    private javax.swing.JCheckBox METHOD_OF_CONTACT_TELEGRAM;
    private javax.swing.JButton OPEN_DETAILS_WINDOW_BUTTON;
    private javax.swing.ButtonGroup PREVIOUS_COMISSIONER_BUTTON_GROUP;
    private javax.swing.JLabel PREVIOUS_COMMISSIONER;
    private javax.swing.JRadioButton PREVIOUS_COMMISSIONER_NO;
    private javax.swing.JRadioButton PREVIOUS_COMMISSIONER_YES;
    private javax.swing.JLabel PRICE_CHARGED;
    private javax.swing.JTextField PRICE_CHARGED_AMMOUNT;
    private javax.swing.JComboBox<String> PRICE_CHARGED_CURRENCY;
    private javax.swing.JLabel USERNAME;
    private javax.swing.JTextField USERNAME_TEXT;
    private javax.swing.JLabel WRITTEN_DETAILS;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
