/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.tartarus.customers;
import javax.swing.text.*;
import javax.swing.*;
import java.io.File;
import java.awt.Desktop;
import my.tartarus.artists.MainUI;
/**
 *
 * @author Soerakraven
 */
public class ListCommissionsShowUI extends javax.swing.JFrame {
    int index;
    public static ListCommissionsShowWipUI LCSWUI = new ListCommissionsShowWipUI();
    public static ListCommissionsShowEditUI LCSEUI = new ListCommissionsShowEditUI();
    public static my.tartarus.artists.ShowCustomerDetailsUI SCDUI = new my.tartarus.artists.ShowCustomerDetailsUI();
    /**
     * Creates new form ListCommissionsShowUI
     */
    public ListCommissionsShowUI() {
        initComponents();
    }
    
    public static void HideLCSEUI(){
        LCSEUI.setVisible(false);
    }
    
    public void WriteCommission(int index){
        this.index = index;
        Commissions cm = ManageCommissionerList.comms.get(index);
        this.jTextArea1.setText("");
        this.jTextArea1.append("Commission Title: " + cm.GetCommissionTitle() + "\n");
        this.jTextArea1.append("Artist Username: " + cm.GetArtistusername() + "\n");
        this.jTextArea1.append("Artist Social-media(s): ");
        for(int i=0;i<cm.GetArtistMOC().length;i++){
            this.jTextArea1.append(cm.GetArtistMOC()[i] + ", ");
        }
        this.jTextArea1.append("\n");
        this.jTextArea1.append("Estimate Price: " + cm.GetEstimatePriceCurrency() + " " + cm.GetEstimatePrice() + "\n");
        this.jTextArea1.append("Price Paid: " + cm.GetEstimatePriceCurrency() + " " + cm.GetPricePaid() + "\n");
        this.jTextArea1.append("Payment Platform: " + cm.GetPaymentPlatform() + "\n");
        this.jTextArea1.append("Character Count: " + cm.GetCharacterCount() + "\n");
        this.jTextArea1.append("Character Names: ");
        for(int i=0;i<cm.GetCharacterNames().length;i++){
            this.jTextArea1.append(cm.GetCharacterNames()[i] + ", ");
        }
        this.jTextArea1.append("\n");
        this.jTextArea1.append("Character Type: " + cm.GetCharacterType() + "\n");
        this.jTextArea1.append("Lewds Type: " + cm.GetLewds() + "\n");
        this.jTextArea1.append("Background Included: " + cm.GetBackgroundIncluded() + "\n");
        this.jTextArea1.append("Background Type: " + cm.GetTypeBackground() + "\n");
        this.jTextArea1.append("Wips received: " + cm.GetWipReceived() + "\n");
        this.jTextArea1.append("Deadline Given: " + cm.GetDeadLineGiven() + "\n");
        this.jTextArea1.append("Deadline Date: " + cm.GetDeadlineDate());
    }
    public int ReturnsIndex(){
        return this.index;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        SHOW_ARTIST_TOS_BUTTON = new javax.swing.JButton();
        SHOW_WRITTEN_DETAILS_BUTTON = new javax.swing.JButton();
        SHOW_LATESTWIP_BUTTON = new javax.swing.JButton();
        SHOW_EDIT_BUTTON = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        SHOW_ARTIST_TOS_BUTTON.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        SHOW_ARTIST_TOS_BUTTON.setText("Show Artist TOS");
        SHOW_ARTIST_TOS_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SHOW_ARTIST_TOS_BUTTONActionPerformed(evt);
            }
        });

        SHOW_WRITTEN_DETAILS_BUTTON.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        SHOW_WRITTEN_DETAILS_BUTTON.setText("Show Written Details");
        SHOW_WRITTEN_DETAILS_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SHOW_WRITTEN_DETAILS_BUTTONActionPerformed(evt);
            }
        });

        SHOW_LATESTWIP_BUTTON.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        SHOW_LATESTWIP_BUTTON.setText("Show latest WIP image");
        SHOW_LATESTWIP_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SHOW_LATESTWIP_BUTTONActionPerformed(evt);
            }
        });

        SHOW_EDIT_BUTTON.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        SHOW_EDIT_BUTTON.setText("Edit Commission");
        SHOW_EDIT_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SHOW_EDIT_BUTTONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SHOW_ARTIST_TOS_BUTTON)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SHOW_WRITTEN_DETAILS_BUTTON)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SHOW_LATESTWIP_BUTTON)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SHOW_EDIT_BUTTON)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(SHOW_ARTIST_TOS_BUTTON)
                        .addComponent(SHOW_WRITTEN_DETAILS_BUTTON))
                    .addComponent(SHOW_LATESTWIP_BUTTON)
                    .addComponent(SHOW_EDIT_BUTTON))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SHOW_LATESTWIP_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SHOW_LATESTWIP_BUTTONActionPerformed
        Commissions cm = new Commissions();
        cm = ManageCommissionerList.comms.get(index);
        String path = "wipimages/wip" + cm.GetCommissionTitle() + Integer.toString(index) + ".jpg";
        File f = new File(path);
        try{
            Desktop dt = Desktop.getDesktop();
            dt.open(f);
        }catch (Exception e){
            e.printStackTrace();
            System.out.printf("Something went wrong when opening wip image!");
        }
        /*Commissions cm = new Commissions();
        cm = ManageCommissionerList.comms.get(index);
        ImageIcon icon = new ImageIcon();
        if(cm.GetWipImage()==null){
            JOptionPane.showMessageDialog(new JFrame(), "Either the image failed to load or there's none to be show!");
        }else{
            int width, height;
            icon.setImage(cm.GetWipImage());
            width = icon.getIconWidth();
            height = icon.getIconHeight();
            System.out.printf("%d %d", width, height);
            LCSWUI.setSize(width, height);
            LCSWUI.setVisible(true);
            LCSWUI.SetImage(icon);
        }*/
    }//GEN-LAST:event_SHOW_LATESTWIP_BUTTONActionPerformed

    private void SHOW_EDIT_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SHOW_EDIT_BUTTONActionPerformed
        Commissions cm = new Commissions();
        cm = ManageCommissionerList.comms.get(index);
        LCSEUI.setTitle("Now editing commission " + cm.GetCommissionTitle());
        LCSEUI.WritesCommissionInfo(index);
        LCSEUI.setVisible(true);
    }//GEN-LAST:event_SHOW_EDIT_BUTTONActionPerformed

    private void SHOW_WRITTEN_DETAILS_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SHOW_WRITTEN_DETAILS_BUTTONActionPerformed
        Commissions cm = new Commissions();
        cm = ManageCommissionerList.comms.get(index);
        SCDUI.setTitle("Commission " + cm.GetCommissionTitle() + " details");
        SCDUI.SetText(cm.GetDetails());
        SCDUI.setVisible(true);
    }//GEN-LAST:event_SHOW_WRITTEN_DETAILS_BUTTONActionPerformed

    private void SHOW_ARTIST_TOS_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SHOW_ARTIST_TOS_BUTTONActionPerformed
        Commissions cm = new Commissions();
        cm = ManageCommissionerList.comms.get(index);
        SCDUI.setTitle("Artist " + cm.GetArtistusername() + " TOS");
        SCDUI.SetText(cm.GetTOS());
        SCDUI.setVisible(true);
    }//GEN-LAST:event_SHOW_ARTIST_TOS_BUTTONActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListCommissionsShowUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListCommissionsShowUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListCommissionsShowUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListCommissionsShowUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListCommissionsShowUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SHOW_ARTIST_TOS_BUTTON;
    private javax.swing.JButton SHOW_EDIT_BUTTON;
    private javax.swing.JButton SHOW_LATESTWIP_BUTTON;
    private javax.swing.JButton SHOW_WRITTEN_DETAILS_BUTTON;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
