/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.firstprogram;
    import java.io.*;
    import java.util.*;
    import java.lang.*;
    import java.lang.Object;
    import javax.swing.JFrame;
    import javax.swing.JOptionPane;
    import javax.swing.JPanel;
    import javazoom.jl.player.Player;
    import java.io.File;
    import java.net.MalformedURLException;
    import java.net.URL;
    import javax.swing.JFileChooser;
    import javax.swing.JFrame;
    import java.awt.Desktop;
    import java.net.URI;

/**
 *
 * @author Soerakraven
 */
public class PrincipalUI extends javax.swing.JFrame {
        public DetailsWindowUI novo = new DetailsWindowUI();
    /**
     * Creates new form NumberAdditionUI
     */
    public PrincipalUI () {
        ArchiveClient.CreateFile();
        ArchiveClient.LoadData();
        initComponents();
    }
    public int MOCCounter(){
        int cont=0;
        if(METHOD_OF_CONTACT_DA.isSelected() == true){
            cont++;
        }
        if(METHOD_OF_CONTACT_FA.isSelected() == true){
            cont++;
        }
        if(METHOD_OF_CONTACT_TELEGRAM.isSelected() == true){
            cont++;
        }
        if(METHOD_OF_CONTACT_DISCORD.isSelected() == true){
            cont++;
        }
        if(METHOD_OF_CONTACT_OTHER.isSelected() == true){
            cont++;
        }
        return cont;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PREVIOUS_COMISSIONER_BUTTON_GROUP = new javax.swing.ButtonGroup();
        COMMISSION_COMPLETE_BUTTON_GROUP = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        USERNAME = new javax.swing.JLabel();
        USERNAME_TEXT = new javax.swing.JTextField();
        METHOD_OF_CONTACT = new javax.swing.JLabel();
        METHOD_OF_CONTACT_DISCORD = new javax.swing.JCheckBox();
        METHOD_OF_CONTACT_TELEGRAM = new javax.swing.JCheckBox();
        METHOD_OF_CONTACT_FA = new javax.swing.JCheckBox();
        METHOD_OF_CONTACT_DA = new javax.swing.JCheckBox();
        METHOD_OF_CONTACT_OTHER = new javax.swing.JCheckBox();
        METHOD_OF_CONTACT_OTHER_TEXT = new javax.swing.JTextField();
        PREVIOUS_COMMISSIONER = new javax.swing.JLabel();
        PREVIOUS_COMMISSIONER_YES = new javax.swing.JRadioButton();
        PREVIOUS_COMMISSIONER_NO = new javax.swing.JRadioButton();
        DATE_OF_COMMISSION = new javax.swing.JLabel();
        DATE_OF_COMMISSION_DAY = new javax.swing.JComboBox<>();
        BARRINHA1 = new javax.swing.JLabel();
        DATE_OF_COMMISSION_MONTH = new javax.swing.JComboBox<>();
        BARRINHA2 = new javax.swing.JLabel();
        DATE_OF_COMMISSION_YEAR = new javax.swing.JComboBox<>();
        DATE_OF_PAYMENT = new javax.swing.JLabel();
        DATE_OF_PAYMENT_DAY = new javax.swing.JComboBox<>();
        BARRINHA3 = new javax.swing.JLabel();
        DATE_OF_PAYMENT_MONTH = new javax.swing.JComboBox<>();
        BARRINHA4 = new javax.swing.JLabel();
        DATE_OF_PAYMENT_YEAR = new javax.swing.JComboBox<>();
        INVOICE_NUMBER = new javax.swing.JLabel();
        INVOICE_NUMBER_NUMBER = new javax.swing.JTextField();
        COMMISSION_COMPLETE = new javax.swing.JLabel();
        COMMISSION_COMPLETE_YES = new javax.swing.JRadioButton();
        COMMISSION_COMPLETE_NO = new javax.swing.JRadioButton();
        LIST_CUSTOMERS_BUTTON = new javax.swing.JButton();
        PRICE_CHARGED = new javax.swing.JLabel();
        PRICE_CHARGED_CURRENCY = new javax.swing.JComboBox<>();
        PRICE_CHARGED_AMMOUNT = new javax.swing.JTextField();
        WRITTEN_DETAILS = new javax.swing.JLabel();
        OPEN_DETAILS_WINDOW_BUTTON = new javax.swing.JButton();
        SAVE_BUTTON = new javax.swing.JButton();
        CLEAR_BUTTON = new javax.swing.JButton();
        CREDITS_BUTTON = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(75, 34, 117));
        setResizable(false);

        jPanel1.setForeground(new java.awt.Color(40, 17, 73));

        USERNAME.setBackground(new java.awt.Color(255, 255, 255));
        USERNAME.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        USERNAME.setText("Username");
        USERNAME.setToolTipText("");

        USERNAME_TEXT.setForeground(new java.awt.Color(113, 113, 113));
        USERNAME_TEXT.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        USERNAME_TEXT.setSelectedTextColor(new java.awt.Color(255, 255, 0));
        USERNAME_TEXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USERNAME_TEXTActionPerformed(evt);
            }
        });

        METHOD_OF_CONTACT.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        METHOD_OF_CONTACT.setText("Method of contact");

        METHOD_OF_CONTACT_DISCORD.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        METHOD_OF_CONTACT_DISCORD.setText("Discord");
        METHOD_OF_CONTACT_DISCORD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                METHOD_OF_CONTACT_DISCORDActionPerformed(evt);
            }
        });

        METHOD_OF_CONTACT_TELEGRAM.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        METHOD_OF_CONTACT_TELEGRAM.setText("Telegram");

        METHOD_OF_CONTACT_FA.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        METHOD_OF_CONTACT_FA.setText("FurAffinity");

        METHOD_OF_CONTACT_DA.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        METHOD_OF_CONTACT_DA.setText("Deviantart");

        METHOD_OF_CONTACT_OTHER.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        METHOD_OF_CONTACT_OTHER.setText("Other");
        METHOD_OF_CONTACT_OTHER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                METHOD_OF_CONTACT_OTHERActionPerformed(evt);
            }
        });

        METHOD_OF_CONTACT_OTHER_TEXT.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        METHOD_OF_CONTACT_OTHER_TEXT.setEnabled(false);
        METHOD_OF_CONTACT_OTHER_TEXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                METHOD_OF_CONTACT_OTHER_TEXTActionPerformed(evt);
            }
        });

        PREVIOUS_COMMISSIONER.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        PREVIOUS_COMMISSIONER.setText("Previous Commissioner?");

        PREVIOUS_COMISSIONER_BUTTON_GROUP.add(PREVIOUS_COMMISSIONER_YES);
        PREVIOUS_COMMISSIONER_YES.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        PREVIOUS_COMMISSIONER_YES.setText("Yes");
        PREVIOUS_COMMISSIONER_YES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PREVIOUS_COMMISSIONER_YESActionPerformed(evt);
            }
        });

        PREVIOUS_COMISSIONER_BUTTON_GROUP.add(PREVIOUS_COMMISSIONER_NO);
        PREVIOUS_COMMISSIONER_NO.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        PREVIOUS_COMMISSIONER_NO.setText("No");
        PREVIOUS_COMMISSIONER_NO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PREVIOUS_COMMISSIONER_NOActionPerformed(evt);
            }
        });

        DATE_OF_COMMISSION.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        DATE_OF_COMMISSION.setText("Date of Commission");

        DATE_OF_COMMISSION_DAY.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        DATE_OF_COMMISSION_DAY.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        BARRINHA1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BARRINHA1.setText("/");

        DATE_OF_COMMISSION_MONTH.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        DATE_OF_COMMISSION_MONTH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        BARRINHA2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BARRINHA2.setText("/");

        DATE_OF_COMMISSION_YEAR.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        DATE_OF_COMMISSION_YEAR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028" }));

        DATE_OF_PAYMENT.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        DATE_OF_PAYMENT.setText("Date of Payment");

        DATE_OF_PAYMENT_DAY.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        DATE_OF_PAYMENT_DAY.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        BARRINHA3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BARRINHA3.setText("/");

        DATE_OF_PAYMENT_MONTH.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        DATE_OF_PAYMENT_MONTH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        BARRINHA4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BARRINHA4.setText("/");

        DATE_OF_PAYMENT_YEAR.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        DATE_OF_PAYMENT_YEAR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028" }));
        DATE_OF_PAYMENT_YEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DATE_OF_PAYMENT_YEARActionPerformed(evt);
            }
        });

        INVOICE_NUMBER.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        INVOICE_NUMBER.setText("Number of Invoice");

        INVOICE_NUMBER_NUMBER.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        COMMISSION_COMPLETE.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        COMMISSION_COMPLETE.setText("Commision complete?");

        COMMISSION_COMPLETE_BUTTON_GROUP.add(COMMISSION_COMPLETE_YES);
        COMMISSION_COMPLETE_YES.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        COMMISSION_COMPLETE_YES.setText("Yes");
        COMMISSION_COMPLETE_YES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COMMISSION_COMPLETE_YESActionPerformed(evt);
            }
        });

        COMMISSION_COMPLETE_BUTTON_GROUP.add(COMMISSION_COMPLETE_NO);
        COMMISSION_COMPLETE_NO.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        COMMISSION_COMPLETE_NO.setText("No");
        COMMISSION_COMPLETE_NO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COMMISSION_COMPLETE_NOActionPerformed(evt);
            }
        });

        LIST_CUSTOMERS_BUTTON.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        LIST_CUSTOMERS_BUTTON.setText("CUSTOMERS");
        LIST_CUSTOMERS_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LIST_CUSTOMERS_BUTTONActionPerformed(evt);
            }
        });

        PRICE_CHARGED.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        PRICE_CHARGED.setText("Price Charged");

        PRICE_CHARGED_CURRENCY.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        PRICE_CHARGED_CURRENCY.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADP", "AED", "AFA", "AFN", "ALK", "ALL", "AMD", "ANG", "AOA", "AOK", "AON", "AOR", "ARA", "ARP", "ARS", "ARY", "ATS", "AUD", "AWG", "AYM", "AZM", "AZN", "BAD", "BAM", "BBD", "BDT", "BEC", "BEF", "BEL", "BGJ", "BGK", "BGL", "BGN", "BHD", "BIF", "BMD", "BND", "BOB", "BOP", "BOV", "BRB", "BRC", "BRE", "BRL", "BRN", "BRR", "BSD", "BTN", "BUK", "BWP", "BYB", "BYN", "BYR", "BZD", "CAD", "CDF", "CHC", "CHE", "CHF", "CHW", "CLF", "CLP", "CNX", "CNY", "COP", "COU", "CRC", "CSD", "CSJ", "CSK", "CUC", "CUP", "CVE", "CYP", "CZK", "DDM", "DEM", "DJF", "DKK", "DOP", "DZD", "ECS", "ECV", "EEK", "EGP", "ERN", "ESA", "ESB", "ESP", "ETB", "EUR", "FIM", "FJD", "FKP", "FRF", "GBP", "GEK", "GEL", "GHC", "GHP", "GHS", "GIP", "GMD", "GNE", "GNF", "GNS", "GQE", "GRD", "GTQ", "GWE", "GWP", "GYD", "HKD", "HNL", "HRD", "HRK", "HTG", "HUF", "IDR", "IEP", "ILP", "ILR", "ILS", "INR", "IQD", "IRR", "ISJ", "ISK", "ITL", "JMD", "JOD", "JPY", "KES", "KGS", "KHR", "KMF", "KPW", "KRW", "KWD", "KYD", "KZT", "LAJ", "LAK", "LBP", "LKR", "LRD", "LSL", "LSM", "LTL", "LTT", "LUC", "LUF", "LUL", "LVL", "LVR", "LYD", "MAD", "MDL", "MGA", "MGF", "MKD", "MLF", "MMK", "MNT", "MOP", "MRO", "MTL", "MTP", "MUR", "MVQ", "MVR", "MWK", "MXN", "MXP", "MXV", "MYR", "MZE", "MZM", "MZN", "NAD", "NGN", "NIC", "NIO", "NLG", "NOK", "NPR", "NZD", "OMR", "PAB", "PEH", "PEI", "PEN", "PES", "PGK", "PHP", "PKR", "PLN", "PLZ", "PTE", "PYG", "QAR", "RHD", "ROK", "ROL", "RON", "RSD", "RUB", "RUR", "RWF", "SAR", "SBD", "SCR", "SDD", "SDG", "SDP", "SEK", "SGD", "SHP", "SIT", "SKK", "SLL", "SOS", "SRD", "SRG", "SSP", "STD", "SUR", "SVC", "SYP", "SZL", "THB", "TJR", "TJS", "TMM", "TMT", "TND", "TOP", "TPE", "TRL", "TRY", "TTD", "TWD", "TZS", "UAH", "UAK", "UGS", "UGW", "UGX", "USD", "USN", "USS", "UYI", "UYN", "UYP", "UYU", "UZS", "VEB", "VEF", "VNC", "VND", "VUV", "WST", "XAF", "XAG", "XAU", "XBA", "XBB", "XBC", "XBD", "XCD", "XDR", "XEU", "XFO", "XFU", "XOF", "XPD", "XPF", "XPT", "XRE", "XSU", "XTS", "XUA", "XXX", "YDD", "YER", "YUD", "YUM", "YUN", "ZAL", "ZAR", "ZMK", "ZMW", "ZRN", "ZRZ", "ZWC", "ZWD", "ZWL", "ZWN", "ZWR" }));
        PRICE_CHARGED_CURRENCY.setSelectedIndex(248);

        PRICE_CHARGED_AMMOUNT.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        WRITTEN_DETAILS.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        WRITTEN_DETAILS.setText("Written Details (Include references/links here)");

        OPEN_DETAILS_WINDOW_BUTTON.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        OPEN_DETAILS_WINDOW_BUTTON.setText("Open details window");
        OPEN_DETAILS_WINDOW_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OPEN_DETAILS_WINDOW_BUTTONActionPerformed(evt);
            }
        });

        SAVE_BUTTON.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        SAVE_BUTTON.setText("SAVE");
        SAVE_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVE_BUTTONActionPerformed(evt);
            }
        });

        CLEAR_BUTTON.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        CLEAR_BUTTON.setText("CLEAR");
        CLEAR_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEAR_BUTTONActionPerformed(evt);
            }
        });

        CREDITS_BUTTON.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        CREDITS_BUTTON.setText("CREDITS");
        CREDITS_BUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CREDITS_BUTTONActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(WRITTEN_DETAILS)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(METHOD_OF_CONTACT)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(METHOD_OF_CONTACT_DISCORD)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(METHOD_OF_CONTACT_TELEGRAM)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(METHOD_OF_CONTACT_OTHER))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(USERNAME)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(USERNAME_TEXT))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(METHOD_OF_CONTACT_FA)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(METHOD_OF_CONTACT_DA))
                                .addComponent(PREVIOUS_COMMISSIONER))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(PREVIOUS_COMMISSIONER_YES)
                                    .addGap(9, 9, 9)
                                    .addComponent(PREVIOUS_COMMISSIONER_NO))
                                .addComponent(METHOD_OF_CONTACT_OTHER_TEXT)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(DATE_OF_COMMISSION)
                                .addComponent(DATE_OF_PAYMENT)
                                .addComponent(INVOICE_NUMBER))
                            .addGap(33, 33, 33)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(DATE_OF_COMMISSION_DAY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(BARRINHA1)
                                    .addGap(2, 2, 2)
                                    .addComponent(DATE_OF_COMMISSION_MONTH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(BARRINHA2)
                                    .addGap(2, 2, 2)
                                    .addComponent(DATE_OF_COMMISSION_YEAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(INVOICE_NUMBER_NUMBER, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(DATE_OF_PAYMENT_DAY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(PRICE_CHARGED_AMMOUNT, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(BARRINHA3)
                                    .addGap(3, 3, 3)
                                    .addComponent(DATE_OF_PAYMENT_MONTH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(BARRINHA4)
                                    .addGap(2, 2, 2)
                                    .addComponent(DATE_OF_PAYMENT_YEAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(PRICE_CHARGED)
                            .addGap(6, 6, 6)
                            .addComponent(PRICE_CHARGED_CURRENCY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(OPEN_DETAILS_WINDOW_BUTTON)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(COMMISSION_COMPLETE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(COMMISSION_COMPLETE_YES)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(COMMISSION_COMPLETE_NO))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(SAVE_BUTTON)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CLEAR_BUTTON)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LIST_CUSTOMERS_BUTTON)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CREDITS_BUTTON)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(USERNAME)
                    .addComponent(USERNAME_TEXT, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(METHOD_OF_CONTACT)
                    .addComponent(METHOD_OF_CONTACT_DISCORD)
                    .addComponent(METHOD_OF_CONTACT_TELEGRAM)
                    .addComponent(METHOD_OF_CONTACT_OTHER))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(METHOD_OF_CONTACT_FA)
                    .addComponent(METHOD_OF_CONTACT_DA)
                    .addComponent(METHOD_OF_CONTACT_OTHER_TEXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PREVIOUS_COMMISSIONER, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PREVIOUS_COMMISSIONER_YES)
                    .addComponent(PREVIOUS_COMMISSIONER_NO))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DATE_OF_COMMISSION)
                    .addComponent(DATE_OF_COMMISSION_DAY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DATE_OF_COMMISSION_MONTH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DATE_OF_COMMISSION_YEAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BARRINHA1)
                    .addComponent(BARRINHA2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DATE_OF_PAYMENT)
                    .addComponent(DATE_OF_PAYMENT_DAY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DATE_OF_PAYMENT_MONTH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DATE_OF_PAYMENT_YEAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BARRINHA3)
                    .addComponent(BARRINHA4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(INVOICE_NUMBER)
                    .addComponent(INVOICE_NUMBER_NUMBER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PRICE_CHARGED_CURRENCY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PRICE_CHARGED_AMMOUNT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PRICE_CHARGED))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WRITTEN_DETAILS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(OPEN_DETAILS_WINDOW_BUTTON)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(COMMISSION_COMPLETE)
                    .addComponent(COMMISSION_COMPLETE_YES)
                    .addComponent(COMMISSION_COMPLETE_NO))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LIST_CUSTOMERS_BUTTON)
                    .addComponent(SAVE_BUTTON)
                    .addComponent(CLEAR_BUTTON)
                    .addComponent(CREDITS_BUTTON))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void USERNAME_TEXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USERNAME_TEXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_USERNAME_TEXTActionPerformed

    private void PREVIOUS_COMMISSIONER_YESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PREVIOUS_COMMISSIONER_YESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PREVIOUS_COMMISSIONER_YESActionPerformed

    private void PREVIOUS_COMMISSIONER_NOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PREVIOUS_COMMISSIONER_NOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PREVIOUS_COMMISSIONER_NOActionPerformed

    private void METHOD_OF_CONTACT_DISCORDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_METHOD_OF_CONTACT_DISCORDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_METHOD_OF_CONTACT_DISCORDActionPerformed

    private void DATE_OF_PAYMENT_YEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DATE_OF_PAYMENT_YEARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DATE_OF_PAYMENT_YEARActionPerformed

    private void METHOD_OF_CONTACT_OTHERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_METHOD_OF_CONTACT_OTHERActionPerformed
        if(METHOD_OF_CONTACT_OTHER.isSelected()){
            METHOD_OF_CONTACT_OTHER_TEXT.setEnabled(true);
        }else{
            METHOD_OF_CONTACT_OTHER_TEXT.setEnabled(false);
        }
    }//GEN-LAST:event_METHOD_OF_CONTACT_OTHERActionPerformed

    private void COMMISSION_COMPLETE_YESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COMMISSION_COMPLETE_YESActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_COMMISSION_COMPLETE_YESActionPerformed

    private void COMMISSION_COMPLETE_NOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COMMISSION_COMPLETE_NOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_COMMISSION_COMPLETE_NOActionPerformed

    private void SAVE_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVE_BUTTONActionPerformed
        String[] entradas = new String[9];
        entradas[0] = USERNAME_TEXT.getText();
        int cont2 = 0;
        entradas[1] = "";
        String [] MOC = new String[MOCCounter()];
        if(METHOD_OF_CONTACT_DA.isSelected() == true){
            MOC[cont2] = METHOD_OF_CONTACT_DA.getText();
            cont2++;
        }
        if(METHOD_OF_CONTACT_FA.isSelected() == true){
            MOC[cont2] = METHOD_OF_CONTACT_FA.getText();
            cont2++;
        }
        if(METHOD_OF_CONTACT_TELEGRAM.isSelected() == true){
            MOC[cont2] = METHOD_OF_CONTACT_TELEGRAM.getText();
            cont2++;
        }
        if(METHOD_OF_CONTACT_DISCORD.isSelected() == true){
            MOC[cont2] = METHOD_OF_CONTACT_DISCORD.getText();
            cont2++;
        }
        if(METHOD_OF_CONTACT_OTHER.isSelected() == true){
            MOC[cont2] = METHOD_OF_CONTACT_OTHER_TEXT.getText();
            cont2++;
        }
        if(PREVIOUS_COMMISSIONER_NO.isSelected() == true){
            entradas[2] = PREVIOUS_COMMISSIONER_NO.getText();
        }else{
            entradas[2] = PREVIOUS_COMMISSIONER_YES.getText();
        }
        for(int i=0;i<MOC.length;i++){
            System.out.printf("%s\n", MOC[i]);
        }
        entradas [3] = DATE_OF_COMMISSION_DAY.getSelectedItem().toString() + "/" + DATE_OF_COMMISSION_MONTH.getSelectedItem().toString() + "/" + DATE_OF_COMMISSION_YEAR.getSelectedItem().toString();
        entradas [4] = DATE_OF_PAYMENT_DAY.getSelectedItem().toString() + "/" + DATE_OF_PAYMENT_MONTH.getSelectedItem().toString() + "/" + DATE_OF_PAYMENT_YEAR.getSelectedItem().toString();
        entradas [5] = INVOICE_NUMBER_NUMBER.getText();
        entradas [6] = PRICE_CHARGED_CURRENCY.getSelectedItem().toString();
        entradas [7] = PRICE_CHARGED_AMMOUNT.getText();
        entradas [8] = novo.GetText();
        System.out.printf("I'mhere!\n");
        Customer cus = new Customer(entradas[0], MOC, entradas[2], entradas[3], entradas[4], entradas[5], entradas[6], entradas[7], entradas[8]);
        ManageList.AddCustomer(cus);
        ArchiveClient.WriteFile();
        JOptionPane.showMessageDialog(new JFrame(), "Successfully added!");
    }//GEN-LAST:event_SAVE_BUTTONActionPerformed

    private void METHOD_OF_CONTACT_OTHER_TEXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_METHOD_OF_CONTACT_OTHER_TEXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_METHOD_OF_CONTACT_OTHER_TEXTActionPerformed

    private void CLEAR_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEAR_BUTTONActionPerformed
        USERNAME_TEXT.setText("");
        METHOD_OF_CONTACT_OTHER_TEXT.setEnabled(false);
        METHOD_OF_CONTACT_DA.setSelected(false);
        METHOD_OF_CONTACT_FA.setSelected(false);
        METHOD_OF_CONTACT_TELEGRAM.setSelected(false);
        METHOD_OF_CONTACT_DISCORD.setSelected(false);
        METHOD_OF_CONTACT_OTHER.setSelected(false);
        PREVIOUS_COMMISSIONER_YES.setSelected(false);
        PREVIOUS_COMMISSIONER_NO.setSelected(false);
        INVOICE_NUMBER_NUMBER.setText("");
        PRICE_CHARGED_AMMOUNT.setText("");
        PRICE_CHARGED_CURRENCY.setSelectedIndex(248);
        novo.SetText("");
        
    }//GEN-LAST:event_CLEAR_BUTTONActionPerformed

    private void LIST_CUSTOMERS_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LIST_CUSTOMERS_BUTTONActionPerformed
        ComboBoxUI comb = new ComboBoxUI();
        comb.setVisible(true);
        comb.setTitle("Customer select");
    }//GEN-LAST:event_LIST_CUSTOMERS_BUTTONActionPerformed

    private void OPEN_DETAILS_WINDOW_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OPEN_DETAILS_WINDOW_BUTTONActionPerformed
        novo.setVisible(true);
    }//GEN-LAST:event_OPEN_DETAILS_WINDOW_BUTTONActionPerformed

    private void CREDITS_BUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREDITS_BUTTONActionPerformed
        CreditsUI cd = new CreditsUI();
        cd.setVisible(true);
        cd.setTitle("Credits / All rights reserved");
    }//GEN-LAST:event_CREDITS_BUTTONActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        ArrayList<Customer> customer = new ArrayList<Customer>();
        ManageList.StartList(customer);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PrincipalUI princ = new PrincipalUI();
                princ.setVisible(true);
                princ.setTitle("Tartarus - Written by Soerakraven");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BARRINHA1;
    private javax.swing.JLabel BARRINHA2;
    private javax.swing.JLabel BARRINHA3;
    private javax.swing.JLabel BARRINHA4;
    private javax.swing.JButton CLEAR_BUTTON;
    private javax.swing.JLabel COMMISSION_COMPLETE;
    private javax.swing.ButtonGroup COMMISSION_COMPLETE_BUTTON_GROUP;
    private javax.swing.JRadioButton COMMISSION_COMPLETE_NO;
    private javax.swing.JRadioButton COMMISSION_COMPLETE_YES;
    private javax.swing.JButton CREDITS_BUTTON;
    private javax.swing.JLabel DATE_OF_COMMISSION;
    private javax.swing.JComboBox<String> DATE_OF_COMMISSION_DAY;
    private javax.swing.JComboBox<String> DATE_OF_COMMISSION_MONTH;
    private javax.swing.JComboBox<String> DATE_OF_COMMISSION_YEAR;
    private javax.swing.JLabel DATE_OF_PAYMENT;
    private javax.swing.JComboBox<String> DATE_OF_PAYMENT_DAY;
    private javax.swing.JComboBox<String> DATE_OF_PAYMENT_MONTH;
    private javax.swing.JComboBox<String> DATE_OF_PAYMENT_YEAR;
    private javax.swing.JLabel INVOICE_NUMBER;
    private javax.swing.JTextField INVOICE_NUMBER_NUMBER;
    private javax.swing.JButton LIST_CUSTOMERS_BUTTON;
    private javax.swing.JLabel METHOD_OF_CONTACT;
    private javax.swing.JCheckBox METHOD_OF_CONTACT_DA;
    private javax.swing.JCheckBox METHOD_OF_CONTACT_DISCORD;
    private javax.swing.JCheckBox METHOD_OF_CONTACT_FA;
    private javax.swing.JCheckBox METHOD_OF_CONTACT_OTHER;
    private javax.swing.JTextField METHOD_OF_CONTACT_OTHER_TEXT;
    private javax.swing.JCheckBox METHOD_OF_CONTACT_TELEGRAM;
    private javax.swing.JButton OPEN_DETAILS_WINDOW_BUTTON;
    private javax.swing.ButtonGroup PREVIOUS_COMISSIONER_BUTTON_GROUP;
    private javax.swing.JLabel PREVIOUS_COMMISSIONER;
    private javax.swing.JRadioButton PREVIOUS_COMMISSIONER_NO;
    private javax.swing.JRadioButton PREVIOUS_COMMISSIONER_YES;
    private javax.swing.JLabel PRICE_CHARGED;
    private javax.swing.JTextField PRICE_CHARGED_AMMOUNT;
    private javax.swing.JComboBox<String> PRICE_CHARGED_CURRENCY;
    private javax.swing.JButton SAVE_BUTTON;
    private javax.swing.JLabel USERNAME;
    private javax.swing.JTextField USERNAME_TEXT;
    private javax.swing.JLabel WRITTEN_DETAILS;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
